# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: BI Data Lakehouse Crash Course (2h)
author: thec0dewriter
logo: ""

execute:
  execute_notebooks: off

repository:
  url: https://github.com/thec0dewriter/databricks_free_intro
  path_to_book: .
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
